routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $products = \App\Models\Product::where('active',1)->get();
    return view('welcome',['products'=>$products]);
});
Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'App\Http\Controllers\LanguageController@switchLang']);


Route::get('/cart',[\App\Http\Controllers\CartController::class,'view']);


Route::post('/wishlist/add',[\App\Http\Controllers\WishlistController::class,'add']);
Route::get('/wishlist',[\App\Http\Controllers\WishlistController::class,'view']);
Route::post('/wishlist/remove',[\App\Http\Controllers\WishlistController::class,'remove']);
Route::get('/terms-and-services',function(\Illuminate\Http\Request $req){
   return view('terms');
});
Route::get('/about-us',function(\Illuminate\Http\Request $req){
    return view('aboutUs');
});
Route::get('/contact-us',function(\Illuminate\Http\Request $req){
    return view('contactUs');
});


Route::post('/cart/add',[\App\Http\Controllers\CartController::class,'add']);
Route::post('/cart/remove',[\App\Http\Controllers\CartController::class,'remove']);
Route::get('/product/{product}',[\App\Http\Controllers\ProductController::class,'view'])->where('product','^[a-zA-Z0-9-_\/]+$');
Route::get('/product/{id}/customize',[\App\Http\Controllers\ProductController::class,'customize']);
Route::post('/review/save',[\App\Http\Controllers\ProductController::class,'saveReview']);
Route::get('/products',[\App\Http\Controllers\ProductController::class,'index']);
Route::get('category/{category}',[\App\Http\Controllers\CategoryController::class,'view'])->where('category','^[a-zA-Z0-9-_\/]+$');
Route::get('/special-offers',function(){
   $cat = \App\Models\Category::find(8);
   return view('category',['cat'=>$cat]);
});
Route::get('search',function(\Illuminate\Http\Request $req){
    $products = \App\Models\Product::whereRaw(\Illuminate\Support\Facades\DB::raw('LOWER(title_'.\Illuminate\Support\Facades\App::getLocale() .') LIKE "%'.strtolower($req->txt).'%"'))->get();
    return view('search',['products'=>$products]);

})->name('search');
Route::group(['middleware'=>'auth:web'],function(){
    Route::delete('user/products/pic/{id}/delete', 'App\Http\Controllers\Admin\ProductController@destroyPic');
    Route::get('user/orders', function () {
        return view('user.orders',['user'=>\Illuminate\Support\Facades\Auth::user()]);
    })->name('user.orders');
    Route::get('user/order/{id}',[\App\Http\Controllers\UserController::class,'showOrder'])->name('user.order.show');
    Route::get('/checkout',[\App\Http\Controllers\CartController::class,'checkout']);
    Route::post('/checkout',[\App\Http\Controllers\CartController::class,'saveCheckout']);
    Route::any('/checkout/failed',[\App\Http\Controllers\CartController::class,'failed']);
    Route::any('/checkout/success',[\App\Http\Controllers\CartController::class,'success']);
    Route::get('user/dashboard', function () {
        return view('user.dashboard',['user'=>\Illuminate\Support\Facades\Auth::user()]);
    })->name('user.dashboard');

    Route::get('basket',function(){

    })->name('basket');


    Route::get('user/orders', function () {
        return view('user.orders',['user'=>\Illuminate\Support\Facades\Auth::user()]);
    })->name('user.orders');

    Route::get('user/products', function () {
        return view('user.products',['user'=>\Illuminate\Support\Facades\Auth::user()]);
    })->name('user.products');
//    Route::get('user/order/{id}',[\App\Http\Controllers\UserController::class,'showOrder'])->name('user.order.show');
//    Route::get('user/return/{id}',[\App\Http\Controllers\UserController::class,'showReturn'])->name('user.return.show');
//    Route::get('user/return/create',[\App\Http\Controllers\UserController::class,'createReturn'])->name('user.return.create');
    Route::post('user/order/{id}',[\App\Http\Controllers\UserController::class,'showOrderItems'])->name('user.order.items');
//    Route::post('user/return/{id}',[\App\Http\Controllers\UserController::class,'showReturnItems'])->name('user.return.items');

    Route::get('user/factures', function () {
        return view('user.factures',['user'=>\Illuminate\Support\Facades\Auth::user()]);
    })->name('user.factures');

//    Route::post('user/factures/save',[\App\Http\Controllers\UserController::class,'saveFacture'])->name('user.factures.store');
    Route::get('user/returns', function () {
        return view('user.returns',['user'=>\Illuminate\Support\Facades\Auth::user()]);
    })->name('user.returns');

    Route::get('/user/{id}/orders/list', 'App\Http\Controllers\UserController@ordersList')->name('user.orders.list');
    Route::get('/user/order/{id}/', 'App\Http\Controllers\UserController@order')->name('user.orders.view');
    Route::get('/user/order/{id}/items',[\App\Http\Controllers\UserController::class,'orderItems'])->name('user.order.items');
    Route::get('/user/order/{id}/transactions',[\App\Http\Controllers\UserController::class,'orderTransactions'])->name('user.orders.transactions');
    Route::get('/user/{id}/products/list', 'App\Http\Controllers\UserController@productsList')->name('user.products.list');

    Route::get('/user/products/add',[\App\Http\Controllers\UserController::class,'addProduct']);
    Route::post('/user/products/add',[\App\Http\Controllers\UserController::class,'saveProduct'])->name('user.products.store');
    Route::get('/user/products/{id}/edit',[\App\Http\Controllers\UserController::class,'editProduct'])->name('user.products.edit');
    Route::put('/user/products/{id}/update',[\App\Http\Controllers\UserController::class,'updateProduct'])->name('user.products.update');
//    Route::post('/user/order/item/save', 'App\Http\Controllers\UserController@saveItem')->name('user.order.item.store');
//    Route::delete('/user/order/item/{id}',[App\Http\Controllers\UserController::class,'deleteItem']);
//    Route::get('/user/{id}/returns/list', 'App\Http\Controllers\UserController@returnsList')->name('user.returns.list');
//    Route::post('/user/returns/save', 'App\Http\Controllers\UserController@returnsSave')->name('order.returns.save');
//    Route::get('/user/{id}/factures/list', 'App\Http\Controllers\Admin\FacturesController@index')->name('user.factures.list');

    Route::post('/user/fileUpload',[\App\Http\Controllers\Admin\FileUploadController::class,'fileUpload'])->name('user.fileUpload');
});

Route::any('admin/login', 'App\Http\Controllers\Admin\AuthController@login')->name('admin.login');
Route::any('admin/logout', 'App\Http\Controllers\Admin\AuthController@logout')->name('admin.logout');
Route::group(['prefix'=>'admin', 'middleware' => ['auth:admin']], function (){
    Route::post('products/pic/{id}/default', 'App\Http\Controllers\Admin\ProductController@updateDefaultPic');
    Route::post('fileUpload', 'App\Http\Controllers\Admin\FileUploadController@fileUpload')->name('fileUpload');

    Route::resource('indexCategories', 'App\Http\Controllers\Admin\IndexCategoryController', ['names' => [
        'index' => 'admin.indexCategories.index',
        'create' => 'admin.indexCategories.create',
        'store' => 'admin.indexCategories.store',
        'show' => 'admin.indexCategories.show',
        'edit' => 'admin.indexCategories.edit',
        'update' => 'admin.indexCategories.update',
        'destroy' => 'admin.indexCategories.delete'
    ]]);

    Route::resource('tag', 'App\Http\Controllers\Admin\TagController', ['names' => [
        'index' => 'admin.tag.index',
        'create' => 'admin.tag.create',
        'store' => 'admin.tag.store',
        'show' => 'admin.tag.show',
        'edit' => 'admin.tag.edit',
        'update' => 'admin.tag.update',
        'destroy' => 'admin.tag.delete'
    ]]);
    Route::post('token','App\Http\Controllers\Admin\AdminController@saveFCMToken')->name('admin.token');
    Route::get('dashboard','App\Http\Controllers\Admin\AdminController@dashboard')->name('admin.dashboard');
    Route::post('updateSalesStatus','App\Http\Controllers\Admin\AdminController@salesStatus')->name('admin.salesStatus');
    Route::post('updateCustomProductSalesStatus','App\Http\Controllers\Admin\AdminController@customProductSalesStatus')->name('admin.customProductSalesStatus');
    Route::get('orderCounts','App\Http\Controllers\Admin\AdminController@orderCounts')->name('admin.dashboard.orderCounts');
    Route::get('db/fullBackup','App\Http\Controllers\Admin\AdminController@dbFullBackup')->name('admin.db.fullBackup');

    Route::group(['prefix'=>'custom-product'], function () {
        Route::post('categories/setOrder','App\Http\Controllers\Admin\CustomCategoryController@setOrder')->name('admin.custom.categories.setOrder');
        Route::resource('categories', 'App\Http\Controllers\Admin\CustomCategoryController', ['names' => [
            'index' => 'admin.custom.categories.index',
            'create' => 'admin.custom.categories.create',
            'store' => 'admin.custom.categories.store',
            'show' => 'admin.custom.categories.show',
            'edit' => 'admin.custom.categories.edit',
            'update' => 'admin.custom.categories.update',
            'destroy' => 'admin.custom.categories.delete'
        ]]);



        Route::post('items/setOrder','App\Http\Controllers\Admin\CustomItemController@setOrder')->name('admin.custom.items.setOrder');
        Route::get('items/{id}/rules','App\Http\Controllers\Admin\CustomItemController@rules')->name('admin.custom.items.rules');

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\DB;
use Validator;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class CategoryController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            DB::statement(DB::raw('set @rownum=0'));
            return DataTables::of(Category::select('id','title_en','order',DB::raw('@rownum  := @rownum  + 1 AS rownum'))->orderBy('order','asc'))
                ->addColumn('action', function ($category) {
//                        $res = '<a href="' . route('admin.categories.edit',['id'=>$category->id]) . '" class="btn btn-xs btn-primary"><i class="fa fa-eye fa-fw"></i> مشاهده</a>';
//                    $res = ' <a href="' . route('admin.categories.edit',['id'=>$category->id]) . '?duplicate=true" class="btn btn-xs btn-info"><i class="fa fa-copy fa-fw"></i> کپی</a>';
                    $res = ' <a href="' . route('admin.categories.edit',$category->id) . '" class="btn btn-xs btn-primary waves-effect"><i class="fa fa-pencil fa-fw"></i> Edit</a>';
                    if($category->id!=8)
                        $res = $res . ' <button onclick="deleteItem(' . $category->id . ')" class="btn btn-xs btn-danger btn-delete waves-effect"><i class="fa fa-trash fa-fw"></i> Remove</button>';
                    return $res;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('admin.categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.addEdit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate data
        $validator = Validator::make($request->all(), [
            'title_en' => 'required|string|max:255',
            'active' => 'boolean',

            'slug'=>'required|string|unique:category'
        ]);

        if ($validator->fails()) {
            return response()->json([
                'res' => false,
                'msg' => implode('<br>', $validator->errors()->all())
            ]);
        }

        // create new category
        $category = new Category;

        $category->title_en = trim($request->title_en);
        $category->title_ar = trim($request->title_ar);
        $category->type = $request->type;
        $category->order = @Category::orderBy('order','desc')->first()->order + 1;
        $category->active = trim($request->active);
        $category->show_index = trim($request->show_index);
        $category->show_sidebar = trim($request->show_sidebar);
        $category->parent_id = empty($request->parent_id) ? null : $request->parent_id;
        $category->slug = $request->slug;
        $category->meta_keywords = $request->meta;
        $category->description = $request->desc;

        // check for category image and asign it to category
        if(isset($request->image)) {
            if (asset('upload/temp/' . $request->image)) {
                rename(Config::get('fileuploads.uploadFilePath') . $request->image, Config::get('fileuploads.uploadCategoriesPath') . $request->image);
                $category->image = trim($request->image);
            } else {
                return response()->json([
                    'res' => false,
                    'msg' => 'File not found!'
                ]);
            }
        }

        if ($category->save()) {
            return response()->json([
                'res' => true,
                'msg' => 'Item saved.'
            ]);
        } else
            return response()->json([
                'res' => false,
                'msg' => 'Something went wrong!'
            ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('admin.categories.addEdit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validate data
        $validator = Validator::make($request->all(), [
            'title_en' => 'required|string|max:255',
            'image' => 'nullable',
            'active' => 'boolean',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'res' => false,
                'msg' => implode('<br>', $validator->errors()->all())
            ]);
        }

        // update category
        $category = Category::findOrFail($id);

        $category->title_en = trim($request->title_en);
        $category->title_ar = trim($request->title_ar);
        $category->type = $request->type;
        $category->active = trim($request->active);
        $category->parent_id = empty($request->parent_id) ? null : $request->parent_id;
        $category->show_index = trim($request->show_index);
        $category->show_sidebar = trim($request->show_sidebar);
        $category->slug = $request->slug;
        $category->meta_keywords = $request->meta;
        $category->description = $request->desc;

        // check for category image and asign it to category
        if(isset($request->image)) {
            if (asset('uploads/temp/' . $request->image)) {
                rename(Config::get('fileuploads.uploadFilePath') . $request->image, Config::get('fileuploads.uploadCategoriesPath') . $request->image);
                @unlink(Config::get('fileuploads.uploadCategoriesPath') . $category->image);
                $category->image = trim($request->image);
            } else {
                return response()->json([
                    'res' => false,
                    'msg' => 'File not found!'
                ]);
            }
        }

        if ($category->save()) {
            return response()->json([
                'res' => true,
                'msg' => 'done'
            ]);
        } else
            return response()->json([
                'res' => false,
                'msg' => 'Something went wrong'
            ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Category::findOrFail($id)) {
            Category::destroy($id);
            return response()->json([
                'res' => true,
                'message' => 'Deleted'
            ]);
        } else
            return response()->json([
                'res' => false,
                'message' => 'Something went wrong'
            ]);
    }

        public function setOrder(Request $request)
        {
            foreach ($request->categories as $cat){
                $category = Category::findOrFail($cat['id']);
                $category->order = $cat['newOrder'];
                $category->save();
            }
            return response()->json([
                'res' => true,
                'message' => 'Item order updated.'
            ]);
        }
}

resources/views/admin/categories/addEdit.blade.php
@extends('admin.layouts.panel')

@section('style')
    <link rel="stylesheet" href="{{asset('admin-asset/css/dropzone.min.css')}}">
@endsection

@section('title',' Category')
@section('subtitle',' ')

@section('content')

    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        @if(@$category)
                            Edit Category
                        @else
                            Add Category
                        @endif
                    </h2>
                    {{--<ul class="header-dropdown m-r--5">--}}
                        {{--<li class="dropdown">--}}
                            {{--<a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">--}}
                                {{--<i class="material-icons">more_vert</i>--}}
                            {{--</a>--}}
                            {{--<ul class="dropdown-menu pull-right">--}}
                                {{--<li><a href="javascript:void(0);" class=" waves-effect waves-block">Action</a></li>--}}
                                {{--<li><a href="javascript:void(0);" class=" waves-effect waves-block">Another action</a></li>--}}
                                {{--<li><a href="javascript:void(0);" class=" waves-effect waves-block">Something else here</a></li>--}}
                            {{--</ul>--}}
                        {{--</li>--}}
                    {{--</ul>--}}
                </div>
                <div class="body">
                    <form id="form">
                        <div class="form-group{{ $errors->has('title_en') ? ' has-error' : '' }}">
                            <label for="tbTitle">Title En</label>
                            <div class="form-line">
                                <input type="text" id="tbTitleEn" class="form-control" value="@if(@$category){{$category->title_en}}@endif" placeholder="" required autofocus>
                                @if ($errors->has('title_en'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title_en') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('title_ar') ? ' has-error' : '' }}">
                            <label for="tbTitle">Title Ar</label>
                            <div class="form-line">
                                <input type="text" id="tbTitleAr" class="form-control" value="@if(@$category){{$category->title_ar}}@endif" placeholder="" required autofocus>
                                @if ($errors->has('title_ar'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title_ar') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group ">
                            <label for="sbParent">Parent Category</label>
                            <div class="form-line">
                                <select class="form-control" id="sbParent" >
                                    <option value="0"> No Parent</option>
                                    @foreach(\App\Models\Category::where('active',1)->get() as $cat)
                                        <option value="{{$cat->id}}" @if(@$category) @if($category->parent_id == $cat->id) selected="selected" @endif @endif >
                                            {{$cat->title_en}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                            <label for="tbSlug">Slug</label>
                            <div class="form-line">
                                <input type="text" id="tbSlug" class="form-control" value="@if(@$product){{$product->slug}}@endif" placeholder="" required autofocus>
                                @if ($errors->has('slug'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('slug') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('meta_keywords') ? ' has-error' : '' }}">
                            <label for="tbMeta">Meta Keywords</label>
                            <div class="form-line">
                                <input type="text" id="tbMeta" class="form-control" value="@if(@$product){{$product->meta_keywords}}@endif" placeholder="" required autofocus>
                                @if ($errors->has('meta_keywords'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('meta_keywords') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="tbDesc">Description Meta</label>
                            <div class="form-line">
                                <input type="text" id="tbDesc" class="form-control" value="@if(@$product){{$product->description}}@endif" placeholder="" required autofocus>
                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('active') ? ' has-error' : '' }} clearfix">
                            <label>Status</label>
                            <div>
                                <input type="checkbox" id="chbActive" class="filled-in" @if(@$category->active) checked @endif>
                                <label for="chbActive">Active</label>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('show_sidebar') ? ' has-error' : '' }} clearfix">
                            <label>Show in sidebar</label>
                            <div>
                                <input type="checkbox" id="chShowSidebar" class="filled-in" @if(@$category->show_sidebar) checked @endif>
                                <label for="chShowSidebar">Show</label>
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('show_index') ? ' has-error' : '' }} clearfix">
                            <label>Show index</label>
                            <div>
                                <input type="checkbox" id="cbShowIndex" class="filled-in" @if(@$category->show_index) checked @endif>
                                <label for="cbShowIndex">Show</label>
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('type') ? ' has-error' : '' }} clearfix">
                            <label>Is this cat for Group buy?</label>
                            <div>
                                <input type="checkbox" id="chType" class="filled-in" @if(@$category->type) checked @endif>
                                <label for="chType">Group buy</label>
                            </div>
                        </div>
                        @if(isset($category->image))
                            <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                                <label> Image</label>
                                <div class="row">
                                    <div class="col-xs-6 col-md-3">
                                        <a href="javascript:void(0);" class="thumbnail">
                                            <img src="{{asset('uploads/images/categories/').'/'.$category->image}}" class="img-responsive">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        @endif
                    </form>
                    <form class="dropzone" id="fileUpload"></form>
                    <button type="submit" class="btn btn-primary m-t-15 waves-effect saveBtn">@if(@$category)Save @else Save @endif</button>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('script')


    <!-- Custom Js -->
    <script src="{{ asset('admin-asset/js/dropzone.min.js') }}"></script>

    <script>
        var fileName;
        Dropzone.autoDiscover = false;
        $(function () {
            var fileName;
            $('#form').on('form:submit',function () {
                return false;
            });

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': "{{csrf_token()}}"
                }
            });
            $('.saveBtn').on('click', function () {
//                if ($('#form').parsley().validate())
                    saveItem();
            });
            $(".dropzone").dropzone({
                url: "{{route('fileUpload')}}",
                maxFilesize: 1,
                maxFiles:1,
                init: function() {
                    this.on("success", function(file, responseText) {
                        var t = $.parseJSON( responseText );
                        window.fileName = t.name;
                        console.log(fileName);
                    });
                },
                headers: {
                    'X-CSRF-Token': "{{csrf_token()}}"
                },
                addRemoveLinks: true
            });
        });

        function saveItem() {
            $('.saveBtn').attr('disabled', 'disabled');
            $.ajax(
                {
                    url: '@if(@$category){{route('admin.categories.update',$category->id)}} @else {{route('admin.categories.store')}}@endif',
                    type: @if(@$category)'put'@else'post'@endif,
                    dataType: "JSON",
                    data: {
                        @if(@$category)"id": {{$category->id}},@endif
                        "_method": 'post',
                        "title_en": $('#tbTitleEn').val(),
                        "title_ar": $('#tbTitleAr').val(),
                        "show_sidebar":$('#chShowSidebar').length>0 ? 1:0,
                        "show_index":$('#cbShowIndex').length>0? 1:0,
                        "meta": $('#tbMeta').val(),
                        "desc": $('#tbDesc').val(),
                        "slug": $('#tbSlug').val(),
                        "parent_id":$('#sbParent').val(),
                        "image": fileName,
                        "active": ($('#chbActive:checked').length)? 1 : 0,
                    },
                    success: function (res) {
                        $('.saveBtn').removeAttr('disabled');
                        if (res.res) {
                            $('.alert').remove();
                            $('.body').prepend('<div class="alert alert-success alert-sm alert-dismissable clearfix" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>@if(@$category)Saved!@else Saved!@endif</div>');
                        } else {
                            $('.alert').remove();
                            $('.body').prepend('<div class="alert alert-danger alert-sm alert-dismissable clearfix" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>Error!<br>' + res.msg + '</div>');
                        }
                        setTimeout(function(){
                            $('.alert').fadeOut('slow',function () {
                                $(this).remove();
                            });
                        }, 5000)
                    },
                    error: function (xhr, stat) {
                        $('.saveBtn').removeAttr('disabled');
                        $('.box-header').prepend('<div class="alert alert-danger alert-sm alert-dismissable clearfix"><button type="button" class="close" data-dismiss="alert" aria-label="close">&times;</button>Error!<br>' + res.msg + '</div>');
                    }
                });
        }
    </script>

@endsection